---
title: "analysis log"
output: html_notebook
---

2025-04-21: We got new data from the analysis lab that gives values even if a sample was below the reporting limit. We will use those data to update the previous analyses, which had all assumed that non-detects were zero (i.e., we had used a hurdle model then). Now we know exactly how many non-detects truly were zeros.

2025-04-25: The code `compare new non_detects.R` brings in the updated data and compares it to the original data (i.e., with the lab-required reporting limits). It shows that the sample structures (e.g., replicates, sites, names of samples, etc) are identical. The less stringent reporting limits not added ~60 non-zero values (i.e., before those were coded as non-detect zeros. Now they have concentrations). Most of the data are still zeros (2205 zeros and 633 non-zeros), so we'll use the hurdle model still.

2025-04-26: We re-ran hg4_taxon.rds in the cluster with the new data. It took 15.5 hours to run using a setting of 8 cores, 2000 iterations and 12 threads (I'm not sure if the cluster allowed that many cores though).

2025-04-30: I replotted and made new tables that contain results from the new analysis in model hg4_taxon.rds. The new tables look similar for pfas types that had lots of data to begin with (e.g., PFOS), but need to check numbers for data-poor categories. For example, previous partitioning coefficients for some pfas types were in the 10000's, but are now in the 100's. Need to check if the difference is due to more data in those specific categories.

2025-05-12: Tried to analyze the model with log_kmw as a continuous predictor instead of categorical PFAS. The model had a lot of trouble fitting, but I also concluded that it doesn't make sense to fit this way anyway. First, log_kmw as a continuous predictor implies a log-linear model. That might be reasonable, but it doens't capture any non-linearities the way that the categorical PFAS types do. Additionally, the primary reason for fitting log_kmw is to estimate BAF as a function of log_kmw. But BAF is derived from the model, it's not a response variable. The response variable is concentration and I don't know of a theoretical reason for why concentration should be a linear function of log_kmw (though we could think on this more...I just haven't looked much). Hence it makes sense to instead keep the model as we had it. Use it to get the derived bafs, and then use those as a response with log_kmw as the predictor in a non-linear asymptotic model. Yet more on this...the bafs only apply to organisms/insects and the original model has sediment, water, biofilm, etc. So fitting a separate model to just the organism-level bafs makes the most sense.

2025-05-14: Thinking about how to answer the question 'Is the probability of detection in the water associated with probability of detection in bugs?'. I initially categorized this as detection in water = 0/1, then fit a model with that as the predictor. But it doesn't make sense, because we have site-level data so as long as there is a single detection in water then the site has "1". In other words, there are not comparable categorical predictors of detection

Instead, what we've done is use the hurdle model probabilites as continuous predictors. that way, we calculate the probability of detection in the water vs probability of detection in bugs across posterior itrations. This was cool! We added a 1:1 line and it shows how different pfas have higher or lower probabilites of detection in bugs compared to water, with PFOS falling on the 1:1 line pretty reliably (predictably?). We then repeated it up the food chain, comparing prob in larvae to prob in adults and then prob in adult to prob in spiders. 

2025-05-14: For sum pfas, instead of using the hurdle model to calculate sum pfas, I instead calculated it from the raw data and fit a separate model. this was motivated by the fact that the model predictions we quite high for the larvae/emergers, likely due to the high uncertainty and skewed gamma distributions at each pfas/taxon/site combination. That meant that the central tendency of sum pfas was higher than expected. When using the raw data, these were tamped down and seemed more in line with reasonable expectations.

2025-05-23: For log_kmw, Jess and I discussed some ways to think about it at SFS in San Juan. First, it seems likely that the overabundance of PFOS in the system makes the regression with baf vs log_kmw weak. That's because >50% of the PFAS is coming from PFOS, which represents just a single log_kmw value. In other words, there might not be enough variation in log_kmw to detect a signal. I tried removing PFOS and re-plotting. It doesn't change.

2025-06-03: From email from Jess on 6/2/2025, we want to calculate body burdens using mass data from Kaitlyn. I've created a script '07) body burden.R'. Questions for now...what units are the masses? I assume they're in mg ww, but waiting on Jess to confirm (UPDATE: Units are grams ww). Otherwise the code is written and should work. Our approach for now is to calculate the mean mass per site per bug per stage and then divide that into the posteriors of concentrations. Concentrations are in ppb, which is the same as ng/g. So we first convert bugs to dry mass (multiply by 0.2) then to g and then divide, yielding ng_per_bug.

2025-06-05: Discussion with Jess via Teams. For isotope-tmf analysis, include adults, biofilm, and spiders. Before we had excluded those and included only the insects. For adults, consider adjusting the N15 using Johanna's published corrections. Also consider mean-centering by site before analysis. That way the analysis measures change in concentration over relative change in n15, thereby accounting for variation in the baseline n15.

Examples of subtracting the mean n15 or c13 to allow across site comparisons:

@article{pastor2014temporal,
  title={Temporal variability of nitrogen stable isotopes in primary uptake compartments in four streams differing in human impacts},
  author={Pastor, Ada and Riera, Joan Llu{\'\i}s and Peipoch, Marc and Ca{\~n}as, L{\'\i}dia and Ribot, Miquel and Gacia, Esperan{\c{c}}a and Mart{\'\i}, Eug{\`e}nia and Sabater, Francesc},
  journal={Environmental science \& technology},
  volume={48},
  number={12},
  pages={6612--6619},
  year={2014},
  publisher={ACS Publications}
}

@article{nigro2017stable,
  title={Stable isotope analysis as an early monitoring tool for community-scale effects of rat eradication},
  author={Nigro, Katherine M and Hathaway, Stacie A and Wegmann, Alex S and Miller-ter Kuile, Ana and Fisher, Robert N and Young, Hillary S},
  journal={Restoration Ecology},
  volume={25},
  number={6},
  pages={1015--1025},
  year={2017},
  publisher={Wiley Online Library}
}

@article{woodland2012incorporating,
  title={Incorporating temporally dynamic baselines in isotopic mixing models},
  author={Woodland, Ryan J and Rodr{\'\i}guez, Marco A and Magnan, Pierre and Gl{\'e}met, H{\'e}l{\`e}ne and Cabana, Gilbert},
  journal={Ecology},
  volume={93},
  number={1},
  pages={131--144},
  year={2012},
  publisher={Wiley Online Library}
}


2025-06-11: USGS data. Ground water and surface water. 2) Food web. 3) stable isotopes. 4) body mass.

Analysis - do sumpfas vs n15
Analysis - Convert per mil TMF to per trophic-level tmf. This is harder than it sounds. Well, converting is easy, but interpretation is difficult. If we use biofilm as a baseline, then the trophic levels only range from ~ 1(biofilm) to 1.3. Doing it another way, we can keep n15 on the plots as the x-axis, and instead just calculate what a per trophic level increase would be.

2025-07-22: The models for hg4_taxon and sum pfas all had the wrong data. They did not have the updated data with lower non-detects that Jess had sent in April. I re-ran them with the data from Jess sent on 7/21/2025 and re-made the plots and tables. Results are very close to the originals.

2025-07-23: In writing the models, I noticed that the prior intercept was originally normal(0,1), which would center the prior on exp(0) = 1. However, the data are scaled so that the maximum value is 1 in the response. So this prior doesn't make sense. I re-fit with -2,1, which places most of the weight on small values ~1/10th of the maximum value. 

2025-09-03: For sum pfas in the three-panel figure, the posterior values were wrong. They are now fixed. The issue was a coding mistake that used the taxon-specific mean_sum_ppb to back transform instead of the taxon-free mean_sum_ppb. It's a fairly minor difference, but now the taxon dots scatter around the mean, which makes more sense visually.